# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kplug/kplug.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11kplug/kplug.proto\x12\x05kplug\x1a\x1bgoogle/protobuf/empty.proto\"d\n\x11PluginInformation\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0b\n\x03\x61pi\x18\x04 \x01(\t\x12\x12\n\napiVersion\x18\x05 \x01(\t\"F\n\x17PluginHeartbeatResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x19\n\x11notAcceptedReason\x18\x02 \x01(\t\"\x18\n\x08Resource\x12\x0c\n\x04yaml\x18\x02 \x01(\t\"\xa4\x01\n\tResources\x12\x1d\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x0f.kplug.Resource\x12\x34\n\nreferences\x18\x02 \x03(\x0b\x32 .kplug.Resources.ReferencesEntry\x1a\x42\n\x0fReferencesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.kplug.Resource:\x02\x38\x01\x32Y\n\nController\x12K\n\x0fpluginHeartbeat\x12\x18.kplug.PluginInformation\x1a\x1e.kplug.PluginHeartbeatResponse2\x98\x01\n\x06Plugin\x12,\n\x06\x63reate\x12\x10.kplug.Resources\x1a\x10.kplug.Resources\x12,\n\x06update\x12\x10.kplug.Resources\x1a\x10.kplug.Resources\x12\x32\n\x06\x64\x65lete\x12\x10.kplug.Resources\x1a\x16.google.protobuf.EmptyB$Z\"github.com/tliron/kplug/kplug/grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kplug.kplug_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"github.com/tliron/kplug/kplug/grpc'
  _RESOURCES_REFERENCESENTRY._options = None
  _RESOURCES_REFERENCESENTRY._serialized_options = b'8\001'
  _PLUGININFORMATION._serialized_start=57
  _PLUGININFORMATION._serialized_end=157
  _PLUGINHEARTBEATRESPONSE._serialized_start=159
  _PLUGINHEARTBEATRESPONSE._serialized_end=229
  _RESOURCE._serialized_start=231
  _RESOURCE._serialized_end=255
  _RESOURCES._serialized_start=258
  _RESOURCES._serialized_end=422
  _RESOURCES_REFERENCESENTRY._serialized_start=356
  _RESOURCES_REFERENCESENTRY._serialized_end=422
  _CONTROLLER._serialized_start=424
  _CONTROLLER._serialized_end=513
  _PLUGIN._serialized_start=516
  _PLUGIN._serialized_end=668
# @@protoc_insertion_point(module_scope)
