// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	myorgorgv1alpha1 "github.com/tliron/kplug/examples/database-table/operator/apis/applyconfiguration/myorg.org/v1alpha1"
	scheme "github.com/tliron/kplug/examples/database-table/operator/apis/clientset/versioned/scheme"
	v1alpha1 "github.com/tliron/kplug/examples/database-table/operator/resources/myorg.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatabaseTablesGetter has a method to return a DatabaseTableInterface.
// A group's client should implement this interface.
type DatabaseTablesGetter interface {
	DatabaseTables(namespace string) DatabaseTableInterface
}

// DatabaseTableInterface has methods to work with DatabaseTable resources.
type DatabaseTableInterface interface {
	Create(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.CreateOptions) (*v1alpha1.DatabaseTable, error)
	Update(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.UpdateOptions) (*v1alpha1.DatabaseTable, error)
	UpdateStatus(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.UpdateOptions) (*v1alpha1.DatabaseTable, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DatabaseTable, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DatabaseTableList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatabaseTable, err error)
	Apply(ctx context.Context, databaseTable *myorgorgv1alpha1.DatabaseTableApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.DatabaseTable, err error)
	ApplyStatus(ctx context.Context, databaseTable *myorgorgv1alpha1.DatabaseTableApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.DatabaseTable, err error)
	DatabaseTableExpansion
}

// databaseTables implements DatabaseTableInterface
type databaseTables struct {
	client rest.Interface
	ns     string
}

// newDatabaseTables returns a DatabaseTables
func newDatabaseTables(c *MyorgV1alpha1Client, namespace string) *databaseTables {
	return &databaseTables{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the databaseTable, and returns the corresponding databaseTable object, and an error if there is any.
func (c *databaseTables) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DatabaseTable, err error) {
	result = &v1alpha1.DatabaseTable{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databasetables").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DatabaseTables that match those selectors.
func (c *databaseTables) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatabaseTableList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DatabaseTableList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databasetables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested databaseTables.
func (c *databaseTables) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("databasetables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a databaseTable and creates it.  Returns the server's representation of the databaseTable, and an error, if there is any.
func (c *databaseTables) Create(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.CreateOptions) (result *v1alpha1.DatabaseTable, err error) {
	result = &v1alpha1.DatabaseTable{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("databasetables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(databaseTable).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a databaseTable and updates it. Returns the server's representation of the databaseTable, and an error, if there is any.
func (c *databaseTables) Update(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.UpdateOptions) (result *v1alpha1.DatabaseTable, err error) {
	result = &v1alpha1.DatabaseTable{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databasetables").
		Name(databaseTable.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(databaseTable).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *databaseTables) UpdateStatus(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.UpdateOptions) (result *v1alpha1.DatabaseTable, err error) {
	result = &v1alpha1.DatabaseTable{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databasetables").
		Name(databaseTable.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(databaseTable).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the databaseTable and deletes it. Returns an error if one occurs.
func (c *databaseTables) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databasetables").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *databaseTables) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databasetables").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched databaseTable.
func (c *databaseTables) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatabaseTable, err error) {
	result = &v1alpha1.DatabaseTable{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("databasetables").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied databaseTable.
func (c *databaseTables) Apply(ctx context.Context, databaseTable *myorgorgv1alpha1.DatabaseTableApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.DatabaseTable, err error) {
	if databaseTable == nil {
		return nil, fmt.Errorf("databaseTable provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(databaseTable)
	if err != nil {
		return nil, err
	}
	name := databaseTable.Name
	if name == nil {
		return nil, fmt.Errorf("databaseTable.Name must be provided to Apply")
	}
	result = &v1alpha1.DatabaseTable{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("databasetables").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *databaseTables) ApplyStatus(ctx context.Context, databaseTable *myorgorgv1alpha1.DatabaseTableApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.DatabaseTable, err error) {
	if databaseTable == nil {
		return nil, fmt.Errorf("databaseTable provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(databaseTable)
	if err != nil {
		return nil, err
	}

	name := databaseTable.Name
	if name == nil {
		return nil, fmt.Errorf("databaseTable.Name must be provided to Apply")
	}

	result = &v1alpha1.DatabaseTable{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("databasetables").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
