// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DatabaseTableStatusApplyConfiguration represents an declarative configuration of the DatabaseTableStatus type for use
// with apply.
type DatabaseTableStatusApplyConfiguration struct {
	Implementation *string `json:"implementation,omitempty"`
}

// DatabaseTableStatusApplyConfiguration constructs an declarative configuration of the DatabaseTableStatus type for use with
// apply.
func DatabaseTableStatus() *DatabaseTableStatusApplyConfiguration {
	return &DatabaseTableStatusApplyConfiguration{}
}

// WithImplementation sets the Implementation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Implementation field is set to the value of the last call.
func (b *DatabaseTableStatusApplyConfiguration) WithImplementation(value string) *DatabaseTableStatusApplyConfiguration {
	b.Implementation = &value
	return b
}
