apiVersion: myorg.org/v1alpha1
kind: DatabaseTable

metadata:
  name: users
  namespace: kplug-example

spec:
  serverName: authorization-cluster
  preferredImplementation: MariaDB

  columns:
  - name: id
    type: uint64
  - name: name
    type: string

  references:
  - apiVersion: myorg.org/v1alpha1
    kind: DatabaseTableMariaDb
    name: users
  - apiVersion: myorg.org/v1alpha1
    kind: DatabaseTablePostgreSql
    name: users

---

apiVersion: myorg.org/v1alpha1
kind: DatabaseTableMariaDb

metadata:
  name: users
  namespace: kplug-example

spec:
  storageEngine: InnoDB

---

apiVersion: myorg.org/v1alpha1
kind: DatabaseTablePostgreSql

metadata:
  name: users
  namespace: kplug-example

spec:
  partitionBy: hash
