apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: databasetablemariadbs.myorg.org

spec:
  group: myorg.org
  names:
    singular: databasetablemariadb
    plural: databasetablemariadbs
    kind: DatabaseTableMariaDb
    listKind: DatabaseTableMariaDbList
    categories:
    - all # will appear in "kubectl get all"
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true # one and only one version must be marked with storage=true
    subresources: # requires CustomResourceSubresources feature gate enabled
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required: [ spec ]
        properties:
          spec:
            type: object
            properties:
              storageEngine:
                type: string
          status:
            type: object
            properties: {}
