apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: postgresqldatabasetables.myorg.org

spec:
  group: myorg.org
  names:
    singular: postgresqldatabasetable
    plural: postgresqldatabasetables
    kind: PostgreSqlDatabaseTable
    listKind: PostgreSqlDatabaseTableList
    categories:
    - all # will appear in "kubectl get all"
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true # one and only one version must be marked with storage=true
    subresources: # requires CustomResourceSubresources feature gate enabled
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required: [ spec ]
        properties:
          spec:
            type: object
            properties:
              partitionBy:
                type: string
          status:
            type: object
            properties:
              partitioned:
                type: boolean

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-table-postgresql-plugin
  namespace: kplug-example
  labels:
    app.kubernetes.io/name: database-table-postgresql-plugin
    app.kubernetes.io/instance: database-table-postgresql-plugin
    app.kubernetes.io/component: plugin
    app.kubernetes.io/part-of: Kplug
    app.kubernetes.io/managed-by: Kplug

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: database-table-postgresql-plugin
      app.kubernetes.io/instance: database-table-postgresql-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database-table-postgresql-plugin
        app.kubernetes.io/instance: database-table-postgresql-plugin
        app.kubernetes.io/component: plugin
        app.kubernetes.io/part-of: Kplug
        app.kubernetes.io/managed-by: Kplug
    spec:
      serviceAccount: database-table-operator
      containers:
      - name: operator
        image: docker.io/tliron/kplug-database-table-postgresql-plugin:latest
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50050

---

apiVersion: v1
kind: Service

metadata:
  name: database-table-postgresql-plugin
  namespace: kplug-example

spec:
  selector:
    app.kubernetes.io/name: database-table-postgresql-plugin
    app.kubernetes.io/instance: database-table-postgresql-plugin
  ports:
  - name: grpc
    protocol: TCP
    port: 50050
    targetPort: grpc
