#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

git_version

cd examples/database-table/operator/database-table-operator

go install \
	-ldflags " \
		-X 'github.com/tliron/kutil/version.GitVersion=$VERSION' \
		-X 'github.com/tliron/kutil/version.GitRevision=$REVISION' \
		-X 'github.com/tliron/kutil/version.Timestamp=$TIMESTAMP'"
