#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

# sudo dnf install protobuf-compiler protobuf-devel
# go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
# go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
# pip install grpcio-tools

OUT=$ROOT/kplug/grpc

if [ "$1" == -c ]; then
	rm --recursive --force "$OUT"
fi

mkdir --parents "$OUT"

protoc \
	kplug.proto \
	--proto_path="$ROOT/assets/grpc" \
	--go_out="$OUT" \
	--go-grpc_out="$OUT" \
	--go_opt=paths=source_relative \
	--go-grpc_opt=paths=source_relative

cd "$ROOT/sdk/python"

cp "$ROOT/assets/grpc/kplug.proto" kplug/

python -m grpc_tools.protoc \
	kplug/kplug.proto \
	--proto_path=. \
	--python_out=. \
	--grpc_python_out=.

rm kplug/kplug.proto
