// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tliron/kplug/examples/database-table/operator/resources/myorg.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDatabaseTables implements DatabaseTableInterface
type FakeDatabaseTables struct {
	Fake *FakeMyorgV1alpha1
	ns   string
}

var databasetablesResource = schema.GroupVersionResource{Group: "myorg.org", Version: "v1alpha1", Resource: "databasetables"}

var databasetablesKind = schema.GroupVersionKind{Group: "myorg.org", Version: "v1alpha1", Kind: "DatabaseTable"}

// Get takes name of the databaseTable, and returns the corresponding databaseTable object, and an error if there is any.
func (c *FakeDatabaseTables) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DatabaseTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(databasetablesResource, c.ns, name), &v1alpha1.DatabaseTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseTable), err
}

// List takes label and field selectors, and returns the list of DatabaseTables that match those selectors.
func (c *FakeDatabaseTables) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatabaseTableList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(databasetablesResource, databasetablesKind, c.ns, opts), &v1alpha1.DatabaseTableList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DatabaseTableList{ListMeta: obj.(*v1alpha1.DatabaseTableList).ListMeta}
	for _, item := range obj.(*v1alpha1.DatabaseTableList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested databaseTables.
func (c *FakeDatabaseTables) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(databasetablesResource, c.ns, opts))

}

// Create takes the representation of a databaseTable and creates it.  Returns the server's representation of the databaseTable, and an error, if there is any.
func (c *FakeDatabaseTables) Create(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.CreateOptions) (result *v1alpha1.DatabaseTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(databasetablesResource, c.ns, databaseTable), &v1alpha1.DatabaseTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseTable), err
}

// Update takes the representation of a databaseTable and updates it. Returns the server's representation of the databaseTable, and an error, if there is any.
func (c *FakeDatabaseTables) Update(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.UpdateOptions) (result *v1alpha1.DatabaseTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(databasetablesResource, c.ns, databaseTable), &v1alpha1.DatabaseTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseTable), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDatabaseTables) UpdateStatus(ctx context.Context, databaseTable *v1alpha1.DatabaseTable, opts v1.UpdateOptions) (*v1alpha1.DatabaseTable, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(databasetablesResource, "status", c.ns, databaseTable), &v1alpha1.DatabaseTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseTable), err
}

// Delete takes name of the databaseTable and deletes it. Returns an error if one occurs.
func (c *FakeDatabaseTables) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(databasetablesResource, c.ns, name, opts), &v1alpha1.DatabaseTable{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDatabaseTables) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(databasetablesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DatabaseTableList{})
	return err
}

// Patch applies the patch and returns the patched databaseTable.
func (c *FakeDatabaseTables) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatabaseTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(databasetablesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DatabaseTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseTable), err
}
