// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tliron/kplug/examples/database-table/operator/apis/clientset/versioned/typed/myorg.org/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMyorgV1alpha1 struct {
	*testing.Fake
}

func (c *FakeMyorgV1alpha1) DatabaseTables(namespace string) v1alpha1.DatabaseTableInterface {
	return &FakeDatabaseTables{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMyorgV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
