// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/tliron/kplug/examples/database-table/operator/apis/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DatabaseTables returns a DatabaseTableInformer.
	DatabaseTables() DatabaseTableInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DatabaseTables returns a DatabaseTableInformer.
func (v *version) DatabaseTables() DatabaseTableInformer {
	return &databaseTableInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
