// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DatabaseTableListerExpansion allows custom methods to be added to
// DatabaseTableLister.
type DatabaseTableListerExpansion interface{}

// DatabaseTableNamespaceListerExpansion allows custom methods to be added to
// DatabaseTableNamespaceLister.
type DatabaseTableNamespaceListerExpansion interface{}
